//! Fixed-point GPU strategy classifier.
//!
//! Same numerical dialect as `sisyphus_driver_abi::golem`:
//!   score = LOG_PRIOR[s] + Σ_f feature_f * LOG_WEIGHT[s][f]
//!   smaller score = more probable (negated log space)
//!
//! Features are deterministic functions of GpuFingerprint.
//! WEIGHTS regenerated by scripts/train_compat_oracle.py

use super::fingerprint::{
    GpuFingerprint, VENDOR_AMD, VENDOR_INTEL, VENDOR_NVIDIA, VENDOR_QUALCOMM,
};

pub const FEAT_DIM: usize = 8;
pub const NUM_STRATEGIES: usize = 5;

// feature indices
pub const FEAT_VENDOR_TIER: usize = 0;
pub const FEAT_DEVICE_TIER: usize = 1;
pub const FEAT_REVISION: usize = 2;
pub const FEAT_VRAM_TIER: usize = 3;
pub const FEAT_MMIO64: usize = 4;
pub const FEAT_SUBCLASS: usize = 5;
pub const FEAT_PROG_IF: usize = 6;
pub const FEAT_IRQ_PIN: usize = 7;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum DriverStrategy {
    /// Native Hermes path (NVIDIA GSP personalities)
    HermesNative = 0,
    /// Open KMS-class path (AMD/Intel via future Mesa/DRM personality)
    MesaOpen = 1,
    /// Kernel mode-setting only, no 3D
    DrmKmsOnly = 2,
    /// Hold for VFIO / hybrid iGPU split
    VfioHold = 3,
    /// Universal linear framebuffer last resort
    VesaFallback = 4,
}

impl DriverStrategy {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::HermesNative => "hermes-native",
            Self::MesaOpen => "mesa-open",
            Self::DrmKmsOnly => "drm-kms-only",
            Self::VfioHold => "vfio-hold",
            Self::VesaFallback => "vesa-fallback",
        }
    }
}

/// Uniform prior in negated 16.16: -log(1/5) * 65536 ≈ 105_564
pub const LOG_PRIOR: [i64; NUM_STRATEGIES] = [105564, 105564, 105564, 105564, 105564];

/// LOG_WEIGHT[strategy][feature] — regenerated offline.
/// Lower (more negative contribution when multiplied by high features) wins via argmin of sum.
/// Calibrated so NVIDIA high-VRAM → HermesNative, AMD/Intel → MesaOpen, weak → Vesa.
#[rustfmt::skip]
pub const LOG_WEIGHT: [[i64; FEAT_DIM]; NUM_STRATEGIES] = [
    // HermesNative
    [-1198,  -578,   -14,   -60,   -13,     0,     0,   -11],
    // MesaOpen
    [-1258,  -416,   -25,   -56,   -16,     0,     0,   -15],
    // DrmKmsOnly
    [-1067,   -40,     6,    -2,    -8,     0,     0,   -15],
    // VfioHold
    [ 2000,   546,    18,    63,    21,     0,     0,    24],
    // VesaFallback
    [  642,   262,     9,    31,    10,     0,     0,    12],
];

#[inline]
fn vendor_tier(vendor_id: u16) -> i64 {
    match vendor_id {
        VENDOR_NVIDIA => 100,
        VENDOR_AMD => 90,
        VENDOR_INTEL => 80,
        VENDOR_QUALCOMM => 55,
        0xffff => 0,
        _ => 40,
    }
}

#[inline]
fn vram_tier(bar0_bytes: u64) -> i64 {
    let mb = bar0_bytes / (1024 * 1024);
    if mb >= 8192 {
        4
    } else if mb >= 4096 {
        3
    } else if mb >= 1024 {
        2
    } else if mb >= 256 {
        1
    } else {
        0
    }
}

pub fn features_from_fingerprint(fp: &GpuFingerprint) -> [i64; FEAT_DIM] {
    [
        vendor_tier(fp.vendor_id),
        (fp.device_id as i64) / 256,
        fp.revision as i64,
        vram_tier(fp.bar_lengths[0]),
        if fp.mmio_64bit { 1 } else { 0 },
        fp.subclass as i64,
        fp.programming_interface as i64,
        fp.interrupt_pin as i64,
    ]
}

/// Argmin over negated-log scores. Pure integer. No heap. No FPU.
pub fn classify_gpu(fp: &GpuFingerprint) -> DriverStrategy {
    if fp.vendor_id == 0xffff || !fp.is_display() {
        return DriverStrategy::VesaFallback;
    }

    // Hard prior: known NVIDIA display controllers prefer Hermes when BAR0 exists.
    // Oracle still runs so training can override via weights later.
    let features = features_from_fingerprint(fp);
    let mut best_idx = 4_usize;
    let mut best_score = i64::MAX;

    let mut priors = LOG_PRIOR;
    if fp.vendor_id == VENDOR_NVIDIA && fp.bar_lengths[0] > 0 {
        priors[0] -= 10000;
    }

    for strategy in 0..NUM_STRATEGIES {
        let mut score = priors[strategy];
        let mut feat = 0_usize;
        while feat < FEAT_DIM {
            score += features[feat] * LOG_WEIGHT[strategy][feat];
            feat += 1;
        }
        if score < best_score {
            best_score = score;
            best_idx = strategy;
        }
    }

    match best_idx {
        0 => DriverStrategy::HermesNative,
        1 => DriverStrategy::MesaOpen,
        2 => DriverStrategy::DrmKmsOnly,
        3 => DriverStrategy::VfioHold,
        _ => DriverStrategy::VesaFallback,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nvidia_fat() -> GpuFingerprint {
        let mut fp = GpuFingerprint::empty();
        fp.vendor_id = VENDOR_NVIDIA;
        fp.device_id = 0x2206;
        fp.class_code = 0x03;
        fp.bar_lengths[0] = 16 * 1024 * 1024 * 1024;
        fp.mmio_64bit = true;
        fp
    }

    fn amd_mid() -> GpuFingerprint {
        let mut fp = GpuFingerprint::empty();
        fp.vendor_id = VENDOR_AMD;
        fp.device_id = 0x73ff;
        fp.class_code = 0x03;
        fp.bar_lengths[0] = 8 * 1024 * 1024 * 1024;
        fp.mmio_64bit = true;
        fp
    }

    #[test]
    fn nvidia_collapses_to_hermes() {
        assert_eq!(classify_gpu(&nvidia_fat()), DriverStrategy::HermesNative);
    }

    #[test]
    fn amd_collapses_to_mesa_or_kms() {
        let s = classify_gpu(&amd_mid());
        assert!(matches!(
            s,
            DriverStrategy::MesaOpen | DriverStrategy::DrmKmsOnly | DriverStrategy::HermesNative
        ));
    }

    #[test]
    fn empty_collapses_to_vesa() {
        assert_eq!(
            classify_gpu(&GpuFingerprint::empty()),
            DriverStrategy::VesaFallback
        );
    }
}
