#!/usr/bin/env python3
# scripts/train_compat_oracle.py
"""Regenerate LOG_WEIGHT for kernel/boulder/src/drivers/drivernet/compat_oracle.rs

Feature vector (must match FEAT_*):
  [vendor_tier, device_tier, revision, vram_tier, mmio64, subclass, prog_if, irq_pin]

Strategies:
  0 HermesNative, 1 MesaOpen, 2 DrmKmsOnly, 3 VfioHold, 4 VesaFallback
"""

from __future__ import annotations
import numpy as np

# hand-labeled seed corpus — extend from pci.ids + lab machines
# (features, strategy_index)
SAMPLES: list[tuple[list[int], int]] = [
    # NVIDIA RTX 3080
    ([100, 34, 1, 4, 1, 0, 0, 1], 0),
    # NVIDIA RTX 4090
    ([100, 40, 1, 4, 1, 0, 0, 1], 0),
    # NVIDIA GT 710 (weak)
    ([100, 4, 0, 1, 0, 0, 0, 1], 2),
    # AMD RX 7900 XTX
    ([90, 28, 0, 4, 1, 0, 0, 1], 1),
    # AMD RX 6600
    ([90, 28, 0, 3, 1, 0, 0, 1], 1),
    # Intel Arc A770
    ([80, 22, 4, 3, 1, 0, 0, 1], 1),
    # Intel UHD iGPU
    ([80, 17, 0, 1, 1, 0, 0, 1], 2),
    # Qualcomm Adreno
    ([55, 8, 0, 1, 1, 0, 0, 1], 2),
    # unknown VGA
    ([40, 1, 0, 0, 0, 0, 0, 0], 4),
    # empty
    ([0, 0, 0, 0, 0, 0, 0, 0], 4),
]

STRATEGIES = [
    "HermesNative",
    "MesaOpen",
    "DrmKmsOnly",
    "VfioHold",
    "VesaFallback",
]
FEAT = 8
N = 5

def main() -> None:
    # One-vs-rest linear scores → integer weights.
    # Target: for correct class, feature·w should be strongly negative.
    weights = np.zeros((N, FEAT), dtype=np.float64)
    counts = np.zeros(N, dtype=np.float64)

    for feats, label in SAMPLES:
        x = np.asarray(feats, dtype=np.float64)
        counts[label] += 1.0
        # pull correct class toward -x (lower score)
        weights[label] -= x
        # push others slightly toward +x
        for s in range(N):
            if s != label:
                weights[s] += 0.15 * x

    # normalize by class support
    for s in range(N):
        if counts[s] > 0:
            weights[s] /= counts[s]

    # scale to i64-ish range comparable to golem tables
    scaled = np.clip(np.rint(weights * 20.0), -2000, 2000).astype(int)

    print("// Generated by scripts/train_compat_oracle.py — do not hand-edit")
    print("#[rustfmt::skip]")
    print("pub const LOG_WEIGHT: [[i64; FEAT_DIM]; NUM_STRATEGIES] = [")
    for s, name in enumerate(STRATEGIES):
        row = ", ".join(f"{v:5d}" for v in scaled[s])
        print(f"    // {name}")
        print(f"    [{row}],")
    print("];")

if __name__ == "__main__":
    main()
